# Header
This is some more **markdown**

In [1]:
import numpy as np

In [11]:
x = np.random.rand(5,3)
x

array([[ 0.32914109,  0.42138283,  0.05369648],
       [ 0.80248981,  0.15859938,  0.26194957],
       [ 0.44059166,  0.61056112,  0.27677771],
       [ 0.7893831 ,  0.71750831,  0.96902159],
       [ 0.60384004,  0.40611666,  0.15882904]])

In [12]:
x.shape

(5, 3)

In [13]:
x.dtype

dtype('float64')

In [14]:
y = np.random.rand(3,4)
y
# x*y doesnt work because can be any dimensions

array([[ 0.74629347,  0.84738815,  0.98250054,  0.29185814],
       [ 0.90189963,  0.01791672,  0.24129438,  0.26408413],
       [ 0.81420679,  0.0564177 ,  0.66919096,  0.71132039]])

In [15]:
np.dot(x,y)

array([[ 0.6694009 ,  0.28948949,  0.4609918 ,  0.24553842],
       [ 0.95521475,  0.69764053,  1.0020101 ,  0.46242684],
       [ 1.10482981,  0.39990657,  0.76542365,  0.48670739],
       [ 2.02521589,  0.73643925,  1.59716053,  1.10915525],
       [ 0.94623802,  0.52792394,  0.79755378,  0.39646293]])

In [16]:
x = np.mat(x)
y = np.mat(y) # change to matrix
z = x*y
z # allows an overloaded operation, now understands these are 2D matrices

matrix([[ 0.6694009 ,  0.28948949,  0.4609918 ,  0.24553842],
        [ 0.95521475,  0.69764053,  1.0020101 ,  0.46242684],
        [ 1.10482981,  0.39990657,  0.76542365,  0.48670739],
        [ 2.02521589,  0.73643925,  1.59716053,  1.10915525],
        [ 0.94623802,  0.52792394,  0.79755378,  0.39646293]])

In [26]:
x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
x1.dtype

dtype('int64')

In [21]:
print x1[0]

[1 2 3]


In [22]:
print x1[0][1]

2


In [23]:
# 0th row and all columns
x1[0,:]

array([1, 2, 3])

In [24]:
# all rows and 0th column
x1[:,0]

array([1, 4, 7])

In [25]:
# NumPy built on top of C++
# some boolean logic
# I want x1 where this is true
# go to x1, look at all rows and only first column, for middle column > 3, grab rows
x1[x1[:,1]>3]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# running a for loop is slow, has to redo computations
# pandas uses NumPy under hood
# gives all columns 2D array a name
df = pd.DataFrame(data, columns = cols)
df[df.time>1500]